### ISSUE TITLE
Crash on app from playstore

### ISSUE THREAD

**Issue by LucianoFabris** [CleverChuk/mips-mobile-ide#29]
Hello,

I Just Bought the app from playstore and i'm getting this error. Any ideias?
![Screenshot_20200325-134155_mipside](https://user-images.githubusercontent.com/16705053/77562469-d2dfec80-6e9e-11ea-93a3-bfa6aac3a72f.jpg)

**Comment by CleverChuk** [comment]
your string is not formatted properly. the quote is messing it up
![Screenshot_2020-03-26-16-27-07](https://user-images.githubusercontent.com/15526124/77694231-12323a00-6f80-11ea-9a5b-db677ca0c21a.png)

**Comment by LucianoFabris** [comment]
Sorry for this mistake, I'm glad for your help.

**Comment by CleverChuk** [comment]
Thanks for reporting the issue. Even tho your issue was quite a bug it reveal a bug. Thanks a lot!
